release: 0.5.0-alpha.3 (#97)
* codegen metadata

* codegen metadata

* feat(api): api update

* feat(api): api update

* feat(api): api update

* codegen metadata

* feat(api): api update

* feat(api): api update

* release: 0.5.0-alpha.3

* chore(codegen): bump version

---------

Co-authored-by: stainless-app[bot] <142633134+stainless-app[bot]@users.noreply.github.com>
Co-authored-by: Nikhil Benesch <nikhil.benesch@gmail.com>

diff --git a/scripts/lint b/scripts/lint
--- a/scripts/lint
+++ b/scripts/lint
@@ -4,6 +4,14 @@ set -e
 
 cd "$(dirname "$0")/.."
 
+echo "==> Checking for outdated supplemental generated code"
+scripts/gen
+if ! git diff --exit-code; then
+    echo "error: supplemental generated code is out of date" >&2
+    echo " hint: run \`scripts/gen\` to regenerate the code" >&2
+    exit 1
+fi
+
 echo "==> Running lints"
 rye run lint
 
